In [ ]:
#import file from drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#delete column 'torque,name'
#create dataframe and delete column 'torque,name'
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv("drive/Shareddrives/major_project/car.csv")
df.drop(['torque','name'],inplace=True,axis=1)
df.shape

(8128, 11)

In [ ]:
# remove rows with empty columns
df.dropna(inplace=True)
df.shape

(7907, 11)

In [ ]:
#split mileage to give only the value 
new=df['mileage'].str.split(" ",n=1,expand=True)
df['mileage']=new
#split engine to give only the value 
new=df['engine'].str.split(" ",n=1,expand=True)
df['engine']=new
#split max_power to give only the value 
new=df['max_power'].str.split(" ",n=1,expand=True)
df['max_power']=new

In [ ]:
#Adding current year column 
df['Current Year']=2021
# Find no. of years
df['no. of years']=df['Current Year']-df['year']
# drop original and current year
df.drop(['year'],axis=1,inplace=True)
df.drop(['Current Year'],axis=1,inplace=True)
df.head()

   selling_price  km_driven    fuel  ... max_power seats no. of years
0         450000     145500  Diesel  ...        74   5.0            7
1         370000     120000  Diesel  ...    103.52   5.0            7
2         158000     140000  Petrol  ...        78   5.0           15
3         225000     127000  Diesel  ...        90   5.0           11
4         130000     120000  Petrol  ...      88.2   5.0           14

[5 rows x 11 columns]

In [ ]:
#convert objects to numerical values
df['mileage']=df['mileage'].astype(float)
df['seats']=df['seats'].astype(int)
df['engine']=df['engine'].astype(float)
df['max_power']= pd.to_numeric(df['max_power'],errors='coerce')
df.dropna(inplace=True)

In [ ]:
#one hot encoding
df=pd.get_dummies(df,drop_first=True)
df.head()

   selling_price  km_driven  ...  owner_Test Drive Car  owner_Third Owner
0         450000     145500  ...                     0                  0
1         370000     120000  ...                     0                  0
2         158000     140000  ...                     0                  1
3         225000     127000  ...                     0                  0
4         130000     120000  ...                     0                  0

[5 rows x 17 columns]

In [ ]:
#independent and dependent features
x=df.iloc[:,1:]
y=df.iloc[:,0]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=42)
x_test,x_val,y_test,y_val=train_test_split(x_test,y_test,test_size=0.4,random_state=42)

In [ ]:
# x_train.to_csv("drive/Shareddrives/major_project/x_train.csv",index=False)
# x_test.to_csv("drive/Shareddrives/major_project/x_test.csv",index=False)
# x_val.to_csv("drive/Shareddrives/major_project/x_val.csv",index=False)

# y_train.to_csv("drive/Shareddrives/major_project/y_train.csv",index=False)
# y_test.to_csv("drive/Shareddrives/major_project/y_test.csv",index=False)
# y_val.to_csv("drive/Shareddrives/major_project/y_val.csv",index=False)